### ISSUE TITLE
Wandering Trades Mini Block Pricing

### ISSUE THREAD

**Issue by RillSoji** [teakivy/teaks-tweaks#100]
Pricing for mini block seems to be stuck at 1 for 1 even when changed to 1 for 8 in the config file. They will trade 8 times instead. 

Actual behavior: Trade 1 emerald plus 1 block for 1 mini block up to eight times then lock trade.
Expected behavior: Trade 1 emerald plus 1 block for 8 mini blocks once then lock trade
![miniblocks2](https://github.com/user-attachments/assets/dd198a34-a1d6-45bb-b52b-b4138ab13276)
![miniblocks](https://github.com/user-attachments/assets/eb917e1f-5f13-4fdb-a14a-624f043c4d53)

**Comment by teakivy** [comment]
Fixed in the next version. e5cecd48
