### ISSUE TITLE
Change recipe for Bundles to match Vanilla's Experimental (1.21.2)

### ISSUE THREAD

**Issue by SubnovaJH** [teakivy/teaks-tweaks#101]
Mojang has changed the recipe of Bundles to be x1 string & x1 leather instead of x2 string & x6 rabbit hide in their upcoming experimental datapacks for 1.21.2. This may be indicative they will fully implement Bundles into the main release of Java Edition, but nonetheless TeaksTweaks' own recipe for Bundles should potentially reflect this whenever 1.21.2 is released.

Source: https://minecraft.wiki/w/Bundle

![screenshot](https://github.com/user-attachments/assets/075a414f-d5df-4b93-8258-2866e87ff383)

**Comment by teakivy** [comment]
Will be implemented in the next version :)
