### ISSUE TITLE
[Aid Request] Looking for the AFK event used in MC to build an alert for DiscordSRV

### ISSUE THREAD

**Issue by Espressocodes** [teakivy/teaks-tweaks#102]
Hello! 

I use DiscordSRV on my server and I would like to build alerts for the TweaksTweaks packages, but I need some information. For Essentials and CMI they have a event call that I can hook into in order to send a notice whenever the AFK status is added or removed. An example below with what I was attempting to use:

> # Send an AFK alert when someone is AFK / is no longer AFK
> - Trigger: displayAFKMessage
>   Channel: Redacted
>   Conditions:
>    - '#player.hasPermission("teakstweaks.afk.command.afk")'
>   Embed:
>     Author:
>       ImageUrl: "{embedavatarurl}"
>       Name: '${#event.getAffected().getName() + " is " + (#event.value ? "now" : "no longer") + " AFK"}'
>     Timestamp: true

> # Send an AFK alert when someone is AFK / is no longer AFK
> - Trigger: PlayerAFKEvent
>   Channel: Redacted
>   Conditions:
>    - '#player.hasPermission("teakstweaks.afk.command.afk")'
>   Embed:
>     Author:
>       ImageUrl: "{embedavatarurl}"
>       Name: '{username} is ${#event.isGoingAfk() ? "now" : "no longer"} AFK'
>     Timestamp: true

The following is from the Discord SRV documentation of a pre-built event of this type:

> # Send an AFK alert when someone is AFK / is no longer AFK
>   - Trigger: AfkStatusChangeEvent
>     Channel: Redacted
>     Embed:
>       Color: "#869600"
>       Author:
>         ImageUrl: "https://crafthead.net/helm/${#event.getAffected().getUUID()}"
>         Name: '${#event.getAffected().getName() + " is " + (#event.value ? "now" : "no longer") + " AFK"}'

So, I'm not quite sure what event I'm looking for here. I'd also like to know if there's an event list of some sort that the pack uses so that I can build a few generic notifications, but I'm quite stuck! Any help is appreciated here to get the correct call.

**Comment by teakivy** [comment]
Do you know of any plugins that implement a similar system? and/or link documentation from the plugins for how this should be done?

**Comment by Espressocodes** [comment]
> Do you know of any plugins that implement a similar system? and/or link documentation from the plugins for how this should be done?

Yes, of course. Essentials and CMI do it. 

So so sorry for the delay!
[Here's the Discord SRV documentation on hooking into a permission/Event](https://docs.discordsrv.com/alerts)
[Here's the Bukkit Jdoc for event hooks](https://hub.spigotmc.org/javadocs/bukkit/)

Specifically here's the CMI AFK Alert hook:
[CMIAfkEnterEvent.java](https://github.com/Zrips/CMI-API/blob/master/src/com/Zrips/CMI/events/CMIAfkEnterEvent.java)

```
# Send an AFK alert when someone is AFK
  - Trigger: CMIAfkEnterEvent
    Channel: afk
    Embed:
      Color: "#869600"
      Author:
        ImageUrl: "https://crafthead.net/helm/${player.getUniqueId()}"
        Name: '${player.displayName + " is now AFK"}'
```
And essentials:
[AfkStatusChangeEvent.java](https://github.com/EssentialsX/Essentials/blob/master/Essentials/src/main/java/net/ess3/api/events/AfkStatusChangeEvent.java)

```
# Send an AFK alert when someone is AFK / is no longer AFK
  - Trigger: AfkStatusChangeEvent
    Channel: afk
    Embed:
      Color: "#869600"
      Author:
        ImageUrl: "https://crafthead.net/helm/${#event.getAffected().getUUID()}"
        Name: '${#event.getAffected().getName() + " is " + (#event.value ? "now" : "no longer") + " AFK"}'
```
I did try and use a permission for TT to get this to work, but it didn't seem to hook in properly.

**Comment by Espressocodes** [comment]
Saw your commit. I felt a disturbance in the force. Thank you for this. I can't wait to see what you do with the plugin moving forward.

**Comment by teakivy** [comment]
Will be added in the next update, see the wiki (https://github.com/teakivy/teaks-tweaks/wiki/Pack:-AFK-Display#events) for more information.
