### ISSUE TITLE
Individual control over combing/separating Armored Elytras

### ISSUE THREAD

**Issue by Pupstrr** [teakivy/teaks-tweaks#104]
Add separate controls for combining and separating Armored Elytra. That way, you could prevent players from separating elytra after they're made, or only allow separating (useful in cases where Armored Elytra is being removed or switching to a different plugin). There could also be a separate control for the ability to separate legacy armored elytra, that way it can be disabled if an admin knows everyone has a new armored elytra.

**Comment by teakivy** [comment]
Fixed in the next version with permissions
