### ISSUE TITLE
Wandering Trader Spawns Lag Server

### ISSUE THREAD

**Issue by Ozphilo** [teakivy/teaks-tweaks#108]
**Describe the bug**
A clear and concise description of what the bug is. Also include any error messages
The spawning of wandering traders seems to take  up a lot of server resources.

**To Reproduce**
When I test wandering trades I have a contraption that spawns 15 traders at a time so I can get a good idea of the trades and ensure the heads are all present in the config. So spawn 15 traders at a time through dispensers and redstone.

**Expected behavior**
You should notice tps drop a few points and the traders take a while longer to die in lava with some visual "hiccups"

**Screenshots**
![image](https://github.com/user-attachments/assets/acc4dafd-b7c9-4773-afda-ce0fba010172)
![image](https://github.com/user-attachments/assets/81a82aa8-a4bc-4f6f-820d-e4de5a4918cb)
Before Spawning
![image](https://github.com/user-attachments/assets/d71e7bf7-a845-46f4-8201-e636aea77ac9)
After Spawning
![image](https://github.com/user-attachments/assets/26c7b715-68e1-4886-979a-d045b4a040bf)

**Additional context**

**Comment by teakivy** [comment]
Fixed in the next version 🙂
