### ISSUE TITLE
GitHub Project Description

### ISSUE THREAD

**Issue by Loudbooks** [teakivy/teaks-tweaks#124]
It's terrible. It's not grammatically correct. It makes no sense.

If you want to stick strictly to what you have written use "Vanilla Tweaks but it's a plugin!"

Might I suggest some alternatives, too:

- Vanilla Tweaks: Plugin Edition
- Vanilla Tweaks for Spigot based servers

**Comment by teakivy** [comment]
Updated to match Modrinth description
