### ISSUE TITLE
Сopper-powered-rails craft don't work properly

### ISSUE THREAD

**Issue by Vinellon** [teakivy/teaks-tweaks#126]
**Describe the bug**
The crafting rail made of copper does not work, and the crafting looks like in the screenshot.
I think the problem is that the same letter in the file "CopperPoweredRails.java" is used for redstone and copper

**To Reproduce**
1. Enable copper-powered-rails:  enabled: true
2. Try to craft rails

**Screenshots**
![изображение](https://github.com/user-attachments/assets/ba60fdae-0b99-4dc0-a8d2-f7892dcfbaaa)
![изображение](https://github.com/user-attachments/assets/3562d20e-b421-42fb-b6bb-e2f004bae1ce)

**Comment by teakivy** [comment]
Fixed thanks to @mythiccal! will be included in the next release :)
