### ISSUE TITLE
Customizable tool for invisible and item frames

### ISSUE THREAD

**Issue by Vinellon** [teakivy/teaks-tweaks#128]
Hi, I think it would be much more convenient if different tools were used to make a non-fixed item frame and an invisible item frame (since they overlap now). Or, what would be even cooler, add the ability to configure the tool used in the config.

**Comment by teakivy** [comment]
Thanks for the suggestion! I have previously thought about making invisible item frames something you would craft instead of using a tool to fix the conflict. Do you think this would be better than the current implementation, or could it be too confusing?

**Comment by Vinellon** [comment]
> Thanks for the suggestion! I have previously thought about making invisible item frames something you would craft instead of using a tool to fix the conflict. Do you think this would be better than the current implementation, or could it be too confusing?

Personally, I prefer the option of using a tool rather than craft, but you can add the ability to enable this craft)

**Comment by teakivy** [comment]
What would be your suggestion for the default tools for these?

**Comment by teakivy** [comment]
(will add the ability to change it too)

**Comment by Vinellon** [comment]
For un-fixed leave the scissors, and for the invisible maybe a brush?

**Comment by Vinellon** [comment]
https://github.com/teakivy/teaks-tweaks/pull/134

**Comment by teakivy** [comment]
Completed with https://github.com/teakivy/teaks-tweaks/commit/1f1cfb0f081bbb4f7f8f2fadf6603cd696fef10e, as well as changed the item for Invisible Item Frames to the brush

Will be included in the next version
