### ISSUE TITLE
Tweaks seems to interfere with gamerule keepInventory

### ISSUE THREAD

**Issue by Aalwein** [teakivy/teaks-tweaks#13]
I'm running with gamerule keepInventory=true but with Teaks-Tweaks loaded when players die they drop inventory and lose xp. Graves work when enabled, but when disabled keepInventory does not work.

Running with Tweaks 1.6.3 on 1.18 Paper server.

**Comment by teakivy** [comment]
Fixed in v1.6.4-beta
