### ISSUE TITLE
/setblock does not light custom portals

### ISSUE THREAD

**Issue by MiningTcup** [teakivy/teaks-tweaks#138]
**Describe the bug**
With normal portals, using /setblock ~ ~ ~ fire will light them. However, the custom portals from Teak's Tweaks can only be lit using a flint and steel or fire charge.

**To Reproduce**
1. Build a custom portal
2. Stand in it and run /setblock ~ ~ ~ fire
3. It does not light. You can try this with a regular portal and it lights.

**Paste**
[PasteBook](https://pastebook.dev/p/ZbVMm)

**Expected behavior**
The portal should light, just the same as a normal portal.

**Comment by teakivy** [comment]
Thanks for the report! Looking into this, it seems that /setblock isn’t really exposed to spigot’s api, and while it would theoretically be possible, from every way i’ve found it would way overcomplicate it, and end up with more bugs than it’s worth.

Will continue looking into the feasibility of this, but for now marking it as Won’t Fix.

**Comment by MiningTcup** [comment]
Sorry to continue this, but I've found an event that seems to be able to detect setblock and even fill. The only problem is that it triggers for every updated block, not including the main fire block. You can still find the coordinates of the fire, but it triggers more than once.

```Java
@EventHandler
public void onIgnite(BlockPhysicsEvent event) {
    if (event.getChangedType() == Material.AIR) {
        if (event.getSourceBlock().getWorld().getBlockAt(event.getSourceBlock().getLocation()).getType() == Material.FIRE) {
            broadcast(Component.text(event.getSourceBlock().getLocation().toString(), NamedTextColor.AQUA));
        }
    }
}
```

**Comment by teakivy** [comment]
I’ll see how the performance would be with this, but I do know this event often triggers hundreds of times per second, so for such a niche issue i don’t know if it would be worth the performance hit
