### ISSUE TITLE
Iron Trapdoor Recipe Not Correct

### ISSUE THREAD

**Issue by saxon564** [teakivy/teaks-tweaks#139]
**Describe the bug**
The recipe for Iron Trapdoors that is getting registered requires 4 iron trapdoors to make 8 iron trapdoors.
![trapdoors](https://github.com/user-attachments/assets/88e536b7-559e-42e8-98cd-45ed8abece04)

This screenshot is from the MoreIronTrapdoors class which shows that ingredient 'x' is getting set to Material.IRON_TRAPDOOR as opposed to Material.IRON_INGOT

**Comment by teakivy** [comment]
Fixed with #140 will be included in v2.0.6
