### ISSUE TITLE
Multiplayer-sleep skips night during the day

### ISSUE THREAD

**Issue by flappyprince** [teakivy/teaks-tweaks#14]
**config options**
multiplayer-sleep:
    enabled: true
    announce-type: 'chat'
    immediate-chat-display: false
    sleeping-percentage: 0
    boss-bar-color: 'blue'
    always-reset-weather-cycle: false

When clicking a bed the game sets the time to 1000, whatever the time is, instead of only allowing player sleep when it rains or is nighttime. It is also possible to click the bed several times and for each click the message _username went to sleep. Sweat dreams!_ appears in chat. I am not sure if this intended behaviour or not, but the whole chat being filled with the same message is not ideal.

**Comment by teakivy** [comment]
Fixed in v1.6.4-beta
