### ISSUE TITLE
Lastest fix to recipe unregistering caused other plugin's custom recipes to not register in the recipe book

### ISSUE THREAD

**Issue by NeuTraLZero** [teakivy/teaks-tweaks#24]
In my case it's the recipes from these 2 plugins that stopped showing up on book after I updated Teak's Tweaks
[AngelChest](https://www.spigotmc.org/resources/%E2%AD%90-angelchest-plus-%E2%AD%90-death-chests-graveyards.88214/)
[CustomCrafting](https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-16-1-18-premium.95513/)
There are free versions of these plugins in case you might need some testing done
CustomCrafting's recipe still work if you put in the correct ingredients but AngelChest's fetching item recipe stopped working completely

**Comment by teakivy** [comment]
It shouldn’t interact with other plugins at all, but I’ll have a look when I get a chance

**Comment by NeuTraLZero** [comment]
Seems to happen after a vanilla reload command. Is fixed after a restart.

**Comment by teakivy** [comment]
/reload is not recommended by spigot as it can have unintended issues. Therefor this will be marked as "wontfix" unless i can find a simple fix for this. Always restart instead of reload
