### ISSUE TITLE
/afk isn't recognized as a valid command

### ISSUE THREAD

**Issue by alexmcgowan112** [teakivy/teaks-tweaks#25]
The /afk command isn't recognized as a valid command despite it being enabled. Going afk normally does still work though.
When entered, the message 'Unknown command. Type "/help" for help.' shows up

**Comment by teakivy** [comment]
Please ensure afk is still named 'afk' ([here](https://github.com/teakivy/teaks-tweaks/blob/29e50839efb85c76b9ba054cab4e509212caa46b/src/main/resources/data.yml#L177))

Are there any other plugins installed that could be overriding the /afk command? (essentials, afk, etc.)

**Comment by alexmcgowan112** [comment]
It is named correctly and there aren't any plugins that should conflict with it. The server just has DriveBackupV2, LuckPerms, and Voice chat. It's a purpur server if that matters at all.
All other commands seem to work correctly though.

**Comment by teakivy** [comment]
I’ll check on this when I get a chance, I know purpur likes to mess with a lot of things

**Comment by alexmcgowan112** [comment]
Looking back through purpur.yml to adjust something else I noticed that purpur actually does have it's own afk system, so that's most likely the cause of the problem.
