### ISSUE TITLE
More Mob Heads

### ISSUE THREAD

**Issue by flashpaul** [teakivy/teaks-tweaks#35]
I tested the More mob head package and found the following problems:
1- there are 3 heads that when you get them have no skin, but you can see Steve's head: 
       angry pollinated bee
       Cyan Axolot
       Ravager
2- you cannot get the sheep heads (they are not really there in the data file)
3- you can't get Zombified Piglin heads (there are in the file but even killing lots of them and putting a high probability they never drop the head)
4- This is a tip, not a bug. In other plugins on the more mob head, I saw that it was also possible to get the ender dragon head, different from the one you get in the End Cities.

**Comment by teakivy** [comment]
Fixed in 1.7.3-beta [04d1ca4](https://github.com/teakivy/teaks-tweaks/commit/04d1ca45cf916332aa2f69fdd74ac80a96a6d09b)
