### ISSUE TITLE
Can't disable dirt to grass in 1.9.0-beta

### ISSUE THREAD

**Issue by Zaziggi** [teakivy/teaks-tweaks#43]
After disabling the dirt to grass function in the config + reloading the plugin, farmland is still converted to grass when trying to plant seeds.

Deleting the config to generate a fresh one didn't solve it either.

Going back to 1.8.3-beta solved the problem.

Edit: sorry for the wrong label, no idea how to change it.

**Comment by teakivy** [comment]
Will be resolved in v1.9.1-beta (should be releasing later tonight)
