### ISSUE TITLE
Players that are not server operators can't use spawning spheres.

### ISSUE THREAD

**Issue by SERISET** [teakivy/teaks-tweaks#46]
Before anything else, yes, `require-op` is at `false` and I restarted the server. I am on paper 1.19.4 version 540.

Still, players that are not op, when using any command of the spawning spheres, get the message

> You don't have permission to use the command!

By the way, I would appreciate if teleporting to a spawning sphere required a separate permission. I want to allow the creation of spawning spheres, but not teleporting to them.

**Comment by teakivy** [comment]
The config option actually did nothing, as that is now a permission (which you can access via a plugin such as [LuckPerms](https://luckperms.net/)).

The permissions are:
`teakstweaks.spawningspheres.create`

`teakstweaks.spawningspheres.remove`

`teakstweaks.spawningspheres.teleport`

All of which are set to OP by default.
