### ISSUE TITLE
Zombie villagers not dropping heads

### ISSUE THREAD

**Issue by SERISET** [teakivy/teaks-tweaks#52]
I am using 1.10.2-beta, and upon killing zombie villagers with a looting 3 sword, no heads are dropped, despite my data.yml containing

```
zombie-villager:
    chance: 0.5
    looting-bonus: 0.2
```

**Comment by teakivy** [comment]
Fixed, you can redownload the plugin from Modrinth
https://modrinth.com/plugin/teaks-tweaks/version/1.10.2-beta
