### ISSUE TITLE
UnknownHostException in Update Checker causes server to not tick

### ISSUE THREAD

**Issue by lemeow125** [teakivy/teaks-tweaks#58]
**Describe the bug**
The plugin's update checker stops the server from ticking if it fails

**To Reproduce**
1. Run a server
2. Have intermittent internet connection issues
3. Server should show a warning that it has not ticked for 10 seconds if the plugin's update check fails

**Expected behavior**
Plugin update checker should not interfere with server ticking if it fails

**Screenshots**

![image](https://github.com/teakivy/teaks-tweaks/assets/63192778/efb71b15-017c-4301-b7f9-800b2d391888)
![image](https://github.com/teakivy/teaks-tweaks/assets/63192778/15cbeb5c-35bd-4f96-9eb9-70aebd3fc550)

**Additional context**
Running version 1.20.1 on PaperMC build 193

**Plugins List**
![image](https://github.com/teakivy/teaks-tweaks/assets/63192778/58b96d02-296d-4f4a-879c-fd14e2fe825c)

**Comment by teakivy** [comment]
As i don't have a reliable way to test this, I've added an option in the config to completely disable the update checker.

Fixed in v1.10.5-beta
