### ISSUE TITLE
"Chair" block remains when destroyed by non-player

### ISSUE THREAD

**Issue by RillSoji** [teakivy/teaks-tweaks#79]
When a chair stair block is destroyed by a creeper or tnt it does not drop the saddle and technically the "chair" remains. If you place any other block there (even non-stairs) you can then "sit" on it. Not game breaking or anything, just not intended behavior I'm sure. XD Worth noting that removing the stair block with world edit will also have the same no-dropping-saddle-chair-still-there problem.

1. Set down a stair block and smack with saddle to make chair
2. Lure a creeper over to blow up the stair block (stair drops, saddle doesn't)
3. Place a dirt block where stair used to be.
4. Click on the dirt to sit as if it were a stair chair. XD 

**Expected behavior**
Drop the saddle when the block is destroy for *any* reason.

**Comment by teakivy** [comment]
This is now resolved:
https://modrinth.com/plugin/teaks-tweaks/version/1.10.6-beta

(on an additional note, accidentally created this while trying to fix it :P):
[Infinisaddle Bug (Video)](https://github.com/teakivy/teaks-tweaks/assets/53413687/bce74b45-daee-4b6b-8461-527fca515dfd)
