### ISSUE TITLE
Additional "Use" Permission Nodes

### ISSUE THREAD

**Issue by RillSoji** [teakivy/teaks-tweaks#80]
Hey there! Loving the plugin and all the features. I'd like to be able to lock usage of certain features to staff/helpers/ranked players. For example we currently use a different plugin for rotation wrenches. Players can unlock usage by participating in community events. We control this via permission nodes and LuckPerms. I would love to see some additional permission nodes added so we can fully switch over to using Teak's Tweaks instead of keeping the handful of other old and buggy plugins we have to do what TT lacks. 

I would like to see a "use" permission node for each feature ideally. However the ones listed here are specifically what would be useful to my communities: 

teakstweaks.mechanics.bypass - Allow players with this permission to use the /mechanics command even if the config is set to false
teakstweaks.wrenches.use.redstone 
teakstweaks.wrenches.use.terracotta 
teakstweaks.smallify.use
teakstweaks.stairchairs.create 
teakstweaks.stairchairs.destroy 
teakstweaks.stairchairs.use - Allow players to click to sit on stair chairs
teakstweaks.deepslatemining.use 

Thank you for considering!

**Comment by teakivy** [comment]
Hey! I'm currently in the process of rewriting a large portion of Teak's Tweaks and am considering adding a ton of new permissions. 🙂
I'll be sure to add these and others, if you have any more specific permissions you'd like to see, please let me know! I'm open to any suggestions.

**Comment by teakivy** [comment]
These are now all possible in the next version :)
