### ISSUE TITLE
More Mob Head NBT tag

### ISSUE THREAD

**Issue by flashpaul** [teakivy/teaks-tweaks#83]
Hi, I have a problem with More Mob Head.
Basically as soon as I kill the mob I get a head with NBT tag 2. If I place the head and break it however then it has NBT tag 1. Same thing if I use it with Shopkeeper plugin, initially it seems ok. But as soon as I restart it has NBT tag 1. 
![t1](https://github.com/teakivy/teaks-tweaks/assets/44022635/b71ed220-e9e4-4cb3-a8a9-4bf3482516cc)
![t2_break](https://github.com/teakivy/teaks-tweaks/assets/44022635/f0185729-5281-4849-84f4-3c30fd78a3d7)

**Comment by flashpaul** [comment]
I forgot to specify that I put the example of the glow squid here, but it does it with all heads. Thank you

**Comment by teakivy** [comment]
Mob Heads have been rewritten. Resolved in the next version.
