### ISSUE TITLE
[Bug] Chairs are not removed when stair is pushed by a piston

### ISSUE THREAD

**Issue by RillSoji** [teakivy/teaks-tweaks#84]
Placing a piston and pushing the stair block does not remove the "chair" feature nor drop the saddle. This allows any other block to be placed in the spot where the stair was and become a unintentional "chair". 

**To Reproduce**
1. Create a chair per usual 
2. Place a piston and a button to use redstone magic to move the stair block. 
3. Place any other block on the stair's previous location.
4. Click to sit. 

**Expected behavior**
Saddles should pop out and the chair be removed if the stair block is moved. 

![Screenshot_862](https://github.com/teakivy/teaks-tweaks/assets/55805301/7bfe895e-b7c5-494a-8dd0-cde8290642b9)

**Comment by teakivy** [comment]
Resolved once and for all in the next version.
