### ISSUE TITLE
Armored Elytra storage format

### ISSUE THREAD

**Issue by mrmelon54** [teakivy/teaks-tweaks#85]
Why is the Armored Elytra storage format so complicated?

You could just serialize the chestplate and elytra ItemStacks as bytes and store that directly in the parent item.

**Comment by mrmelon54** [comment]
Has there been a new version since this?

**Comment by teakivy** [comment]
> Has there been a new version since this?

Sorry for the delay,
Just released v1.11.0 with this feature :)
