### ISSUE TITLE
Ability for players to know what heads they already collected.

### ISSUE THREAD

**Issue by LouisPhilippeHeon** [teakivy/teaks-tweaks#94]
I have players who are interested in collection every possible mob head. It would be useful for them to have a command to know that heads they don't have yet, or even better, advancements for that, like [this](https://www.curseforge.com/minecraft/customization/all-mob-heads) datapack does.

**Comment by teakivy** [comment]
This will be implemented in the next version :D
![image](https://github.com/user-attachments/assets/d85fcd5e-4b5d-408e-a448-4beca26ac888)
